name: Deploy to Digital ocean droplet

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'
      - 'packages/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: SSH and run commands
        # Updating this requires authentication with SSH keys, see GRAM-766
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_SSH_USER_NAME }}
          password: ${{ secrets.DROPLET_SSH_USER_PASSWORD }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          script: |
            source ~/.nvm/nvm.sh
            nvm use 22.14.0

            cd /root/projects/grammarians/yourbestaccent.com
            echo "PULLING THE CODE - STARTING"
            # disregard local changes, pull the latest code, no matter if the history doesn't match
            # for example because of the force push of an amended commit from inside the instance
            git fetch --all
            git reset --hard origin/main
            echo "PULLING THE CODE - SUCCESS"
            pwd
            echo ${{ secrets.DOPPLER_SERVICE_TOKEN }} | doppler configure set token --scope /root/projects/grammarians/yourbestaccent.com
            corepack enable
            corepack prepare pnpm@10.18.2 --activate
            pnpm install
            pnpm prod:backend:install:ffmpeg
            pnpm prod:backend:build
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} pnpm prod:backend:sentry
            pnpm prod:backend:run
